app:
  name: test-express-app
  port: 3000
  path: ""
  health_check_path: "/ping"

swarm:
  replicas: 3
  # max_replicas_per_node: 5
  # limits:
  #   cpus: 0.25
  #   memory: "256M"

database:
  databases:
    - users
  user:
    name: yasmine
    password: "DBPASSWORD" 


env_vars:
  NODE_ENV: production