app:
  name: big-data-app
  port: 3000
  path: ""
  health_check_path: "/"

swarm:
  replicas: 3
  # max_replicas_per_node: 5
  # limits:
  #   cpus: 0.25
  #   memory: "256M"


env_vars:
  NODE_ENV: production