- name: "common role"
  hosts: all
  roles:
    - common
  tags:
    - base-tasks

- name: "deploy kafka"
  hosts: ingestion
  roles:
    - kafka
  tags:
    - deploy-ingestion

- name: "Set docker swarm manager node IP"
  hosts: all
  tasks:
    - set_fact:
        swarm_master_ip: "{{ item }}"
      when: hostvars[item].swarm_master | default(false) == true
      with_items: "{{ groups['services'] }}"
      run_once: true
  tags:
    - docker-install
    - swarm-manager
    - deploy-webserver
    - deploy-monitoring
    - deploy-app

- name: "deploy docker"
  hosts: 
    - services
    - big_data
    - monitoring
    - querying
  handlers:
  - name: "Restart Docker"
    import_tasks: "roles/docker/handlers/main.yml"
  roles:
    - role: docker
    - role: docker_network_management
      when: platform_env == "local" 
  tags:
    - deploy-docker
    - deploy-app
    - deploy-query-layer
    - deploy-hdfs-spark

- name: "deploy swarm"
  hosts: services
  roles:
    - role: docker-swarm
      when: swarm_master == true
  tags: 
    - swarm-manager
  
- name: "deploy exporters"
  hosts:
    - services
  roles:
    - exporters
  tags:
    - deploy-monitoring
    - deploy-exporters
  
- name: "deploy webserver"
  serial: 1
  hosts:
    - services
    - monitoring
  roles:
    - traefik
  tags:
    - deploy-webserver

- name: "deploy databases for query layer"
  hosts: querying
  roles:
    - databases
  tags:
    - deploy-query-layer

- name: "deploy hdfs and spark"
  hosts: big_data
  roles:
    - hdfs-spark
  tags:
    - deploy-hdfs-spark


- name: "deploy app"
  hosts:
    - services
  roles:
    - app
  tags:
     - deploy-app
