- name: "[METRICS] Install system prerequisites"
  apt:
    name: "{{ metrics_system_packages }}"
    state: present
    # update_cache: yes
  become: true

- name: "[METRICS] Ensure metrics group exists"
  group:
    name: "{{ metrics_group }}"
    state: present
  become: true

- name: "[METRICS] Ensure metrics user exists"
  user:
    name: "{{ metrics_user }}"
    group: "{{ metrics_group }}"
    shell: /usr/sbin/nologin
    create_home: false
    system: yes
  become: true

- name: "[METRICS] Create script and virtual environment parent directory"
  file:
    path: "{{ metrics_script_dir }}"
    state: directory
    owner: "{{ metrics_user }}"
    group: "{{ metrics_group }}"
    mode: '0755'
  become: true

- name: "[METRICS] Copy metrics collector script"
  copy:
    src: metrics/{{ metrics_script_name }} # Assuming script is in "files/metrics/" relative to playbook
    dest: "{{ metrics_script_dir }}/{{ metrics_script_name }}"
    owner: "{{ metrics_user }}"
    group: "{{ metrics_group }}"
    mode: '0755'
  become: true

- name: "[METRICS] Install Python packages into virtual environment"
  ansible.builtin.pip:
    name: "{{ metrics_venv_packages }}"
    virtualenv: "{{ metrics_venv_dir }}"
    virtualenv_command: /usr/bin/python3 -m venv
    state: present
  become: true
  become_user: "{{ metrics_user }}" 

- name: "[METRICS] Copy metrics collector script"
  copy:
    src: metrics/{{ metrics_script_name }}
    dest: "{{ metrics_script_dir }}/{{ metrics_script_name }}"
    owner: "{{ metrics_user }}"
    group: "{{ metrics_group }}"
    mode: '0755'
  become: true

- name: "[METRICS] Deploy systemd unit for metrics collector"
  template:
    src: "{{ metrics_service_template }}"
    dest: "/etc/systemd/system/{{ metrics_service_name }}.service"
    owner: root
    group: root
    mode: '0644'
  become: true


- name: "[METRICS] Enable and start metrics collector service"
  systemd:
    name: "{{ metrics_service_name }}"
    enabled: yes
    state: started
    daemon_reload: yes 
  become: true