
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2.1
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=test
      - DOCKER_INFLUXDB_INIT_PASSWORD=test
      - DOCKER_INFLUXDB_INIT_ORG=fankoush.co
      - DOCKER_INFLUXDB_INIT_BUCKET=system-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=test
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    hostname: elasticsearch
    container_name: elasticsearchCS
    environment:
      - discovery.type=single-node 
      - xpack.security.enabled=false 
    ports:
      - '9200:9200' 
    volumes:
      - es_data:/usr/share/elasticsearch/data


  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    hostname: kibana
    container_name: kibanaCS
    environment:
      - ELASTICSEARCH_USERNAME=test
      - ELASTICSEARCH_PASSWORD=test
      - xpack.security.enabled=false
      - elasticsearch.hosts=http://elasticsearch:9200 
    ports:
      - '5601:5601' 
    volumes:
      - kibana_config:/usr/share/kibana/config
    depends_on:
      - elasticsearch 


volumes:
  influxdb-data:
  es_data:
  kibana_config:


