- name: "[KAFKA] Pull Kafka image"
  docker_image:
    name: "{{ kafka.image }}"
    source: pull
  become: true

- name: "[KAFKA] Run Kafka Docker container"
  docker_container:
    name: "{{ kafka.container_name }}"
    image: "{{ kafka.image }}"
    state: started
    restart_policy: always
    ports: "{{ kafka.ports }}"
    env: "{{ kafka.environment }}"
  become: true

