---
- name: "[COMMON] - Update package manager cache"
  apt:
    update_cache: true
  become: true

- name: "[COMMON] - Install COMMON system packages"
  package:
    name: "{{ COMMON_packages | default([]) }}"
    state: present
  become: true

- name: "[COMMON] - Ensure custom binaries directory exists"
  file:
    path: "{{ custom_bin_path | default('/opt/bin') }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "{{ custom_bin_mode | default('0755') }}"
  become: true

- name: "[COMMON] - Ensure logs directory exists"
  file:
    path: "{{ logs_path | default('/var/log/app') }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "{{ logs_dir_mode | default('0755') }}"
  become: true

- name: "[COMMON] - Configure system hostname"
  hostname:
    name: "{{ system_hostname | default(ansible_hostname) }}"
  become: true
  when: system_hostname is defined and system_hostname != ansible_hostname